### ISSUE TITLE
Opotato - MC 1.16.5: Splitting Plan 丨 拆分计划

### ISSUE THREAD

**Issue by Kasualix** [MCTeamPotato/Kasualix-Issue-Tracker#1]
**English丨英文**

As you can see, Opotato is a massive mod with tons of features and configuration for Minecraft 1.16.5.~1.18.2？Who cares?~
And obviously, some people probably only need one feature of it, but after downloading this mod, they have too many features they don't need (and obviously, these features don't load).
Do you want me to split up the features of Opotato to separate mods?
Which feature(s) do you want?
Simply write it down here, and I will do it. 
If you don't mention it here, I won't do it voluntarily, cuz laziness.
____
**Simplified Chinese丨简体中文**

如你所见，Opotato是一个拥有大量功能和配置的 1.16.5 模组。~1.18.2？Who cares?~
显然，有些人可能只需要它的其中一个功能而已，但下载模组之后，他们却拥有了一大堆根本用不到也不生效的功能。
你想要我把 Opotato 的功能拆分成独立的模组吗？
你想要哪个/些功能？
回复这条 Issue，我就会去做。
你不提，我是不会主动做的，因为懒。

**Comment by A0000Xz** [comment]
能不能把那个灾变配置武器CD什么的拆出来啊，我看着拆出来那个cataclysmfixer只能配置生成率。。。。另外能不能也配置下武器的属性，例如攻击力

**Comment by Kasualix** [comment]
Opotato 2.0.0 release is around the corner, the split plan has ended.

**Comment by SSlav1c** [comment]
split placebo?
