### ISSUE TITLE
Question about Francium

### ISSUE THREAD

**Issue by SiverDX** [MCTeamPotato/Kasualix-Issue-Tracker#10]
The mod which changes some behaviour regarding randoms
I'm using an early version of 2023-07-02 because I had a lot of LegacyRandom crashes
(And after using this mod they stopped appearing)

Is this still WIP? Or abandoned?
Can't seem to find it anymore, last time I saw it there were a lot of additions for other random types / places

**Comment by Kasualix** [comment]
Don't worry, it will be released finally.
Last night some accidents happened to its IDEA workspace (files loss) which makes me desperate about my progress done and so delete the GitHub repo, but now I find a way to restore (a large part of) them.
https://github.com/MCTeamPotato/Francium

**Comment by Kasualix** [comment]
https://modrinth.com/mod/francium-optimization
It's here now, btw.
