### ISSUE TITLE
Sparse Structures not compatible with Alex's Caves

### ISSUE THREAD

**Issue by vivagabe** [MCTeamPotato/Kasualix-Issue-Tracker#100]
Using SS along with AC breaks the caves. it makes the caves really tiny. Hopefully an easy fix!

**Comment by phyne** [comment]
I tested with and without sparse structures active in identical world seeds, and the caves seem to generate ok. Primordial cave was ginormous in each instance, toxic cave was fairly small in each instance. Perhaps just poor luck of the draw. I don't think biome generation has much do to with structure generation.
