### ISSUE TITLE
[Redirector] Incompatibility with Paladin's Furniture

### ISSUE THREAD

**Issue by Bomb787** [MCTeamPotato/Kasualix-Issue-Tracker#101]
It looks like there's a method in Paladin's Furniture that takes an enum value from the BoatEntity class that's causing a crash when used with Redirector.
Minecraft: 1.19.2
Forge: 43.3.5
Redirector: 3.4.0
Paladin's Furniture: 1.2.0
[Crash Report](https://pastebin.com/L800j7YF)

**Comment by Kasualix** [comment]
5.0.0 released, this should be resolved.
