### ISSUE TITLE
1.18.2 World loading crash: Ticking entity: No such method error

### ISSUE THREAD

**Issue by xFirefalconx** [MCTeamPotato/Kasualix-Issue-Tracker#102]
mod version: 0.0.3
any dependencies?? idk
Forge 40.2.14
MC 1.18.2

Modpack. 
See details in logs. 
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/13533860/latest.log)
[crash-2023-12-02_07.22.13-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/13533861/crash-2023-12-02_07.22.13-server.txt)
[crash-2023-12-02_08.21.36-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/13533862/crash-2023-12-02_08.21.36-server.txt)

additional context
I am testing my pack in a "I pull stuff from one folder to another" chaos method right now so I *might* accidently have moved the depencency away, cannot detect whether there is any, though. Some help in that regard as to whether I screwed up or somebody else's mod is doing that would be sublime. Thanks in advance.

**Comment by Kasualix** [comment]
Fixed in [0.0.4](https://legacy.curseforge.com/minecraft/mc-mods/starks/files/4919311) (currently under review)

**Comment by xFirefalconx** [comment]
Thank you! Have a good day.
