### ISSUE TITLE
redirector crash 

### ISSUE THREAD

**Issue by Thunderrock424242** [MCTeamPotato/Kasualix-Issue-Tracker#105]
caused my whole modpack to break. [https://mclo.gs/cFaexLt](https://mclo.gs/cFaexLt)

**Comment by WolfBV** [comment]
<html>
<body>

[20Dec2023 19:47:57.854] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
--
1073 | net.minecraftforge.fml.ModLoadingException: Mod  earchaeology r requires  6minecraft r  o1.19.2 or above, and below 1.20 r
1074 | 7Currently,  6minecraft r 7 is  o1.20.1


</body>
</html>

@Thunderrock424242

**Comment by WolfBV** [comment]
Whatever earcheology is, it requires a minecraft version above 1.19.2 and below 1.20.

**Comment by Thunderrock424242** [comment]
I fixed it

**Comment by Kasualix** [comment]
5.0.0 released, this should be resolved.
