### ISSUE TITLE
[1.16.5] Embeddium Extra Crashing on Server

### ISSUE THREAD

**Issue by MundM2007** [MCTeamPotato/Kasualix-Issue-Tracker#106]
I haven't tested this yet with only EmbeddiumExtra and dependencies, but rather on a bigger modpack, for the Crash Report see https://mclo.gs/xGKaLeA#L698
All mods are updated rn

**Comment by Kasualix** [comment]
Clientside only mod, don't use on servers.

**Comment by Kasualix** [comment]
Clientside only mod, don't use on servers.

**Comment by MundM2007** [comment]
Ok, then it would be great If you could remove the server utility from the categories on curseforge

**Comment by Kasualix** [comment]
> Ok, then it would be great If you could remove the server utility from the categories on curseforge as that's kinda misleading imo

ok thank you for reminding
