### ISSUE TITLE
Opotato - Internal server error

### ISSUE THREAD

**Issue by 2929762171** [MCTeamPotato/Kasualix-Issue-Tracker#110]
### Specific mod for which you open this issue

opotato

### MC version & mod version

opotato-1.16.5-2.2.5

### Latest log

https://pastebin.com/S2xN2dsd

### Issue description

All mods (client)
[modlist.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/13910506/modlist.log)

**Comment by Kasualix** [comment]
Afaik this is a adventive issue of Architectury API, don't think Opotato has anything to do with this.

**Comment by Kasualix** [comment]
Please provide the minimal mod set with which this is able to be reproduced.
I don't think it's an error that Opotato can cause, and architectury is known for [its networking errors](https://github.com/architectury/architectury-api/issues/342).

**Comment by Kasualix** [comment]
[Find the real one](https://github.com/architectury/architectury-api/issues/125)
