### ISSUE TITLE
Zoom.MouseMixin should be final

### ISSUE THREAD

**Issue by NaxefirYT** [MCTeamPotato/Kasualix-Issue-Tracker#113]
### Specific mod for which you open this issue

Embeddium Extras

### MC version & mod version

mc forge 1.16.5, mod v1.11.8

### Latest log

https://gist.github.com/NaxefirYT/38a861f89d651d7a22ba4bcf66fe1327

### Issue description

```
@Final field field_198046_k:Lnet/minecraft/client/util/MouseSmoother; in embeddiumextras.mixins.json:zoom.MouseMixin should be final
@Final field field_198047_l:Lnet/minecraft/client/util/MouseSmoother; in embeddiumextras.mixins.json:zoom.MouseMixin should be final
```

**Comment by Kasualix** [comment]
this is harmless
