### ISSUE TITLE
Two bugs: 1# game crashes if your modifier config has different mods with same value, #2 mod stops registering modifier configs for bows/curio/shield

### ISSUE THREAD

**Issue by DezZzO** [MCTeamPotato/Kasualix-Issue-Tracker#117]
### Specific mod for which you open this issue

Remodifier

### MC version & mod version

1.19.2, remodifier-1.19.2-2.2.1

### Latest log

Crashlog for #1 - https://pastebin.com/P3Hwb1Ts, latest for #2 attached, too large for pastebin

### Issue description

Example config for crash recreation number 1:
{"name":"guarding","weight":200,"attributes":"minecraft:generic.armor;minecraft:generic.armor_toughness","amounts":"2;2","operationId":"0;0"}

Expected behavior for 1: possibility of having the same value for different stats in a multistat modifier

Expected behavior for 2: for mod to register modifiers
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/14139879/latest.log)

**Comment by Kasualix** [comment]
[unzip me.zip](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/14140625/unzip.me.zip)
Can you try if this build fix the first issue? I'm not sure whether or not the second is fixed

**Comment by Kasualix** [comment]
For the second issue, is it only the json file in the directories that can't accomplish the registration, and is the entry in toml able to take effect?

**Comment by Kasualix** [comment]
[unzip me.zip](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/14141288/unzip.me.zip)
How about this build? I also add some more debug info here so it would be nice if you can upload your latest.log again if it still doesn't work on that version

**Comment by Kasualix** [comment]
Can you share your configs?

**Comment by Kasualix** [comment]
I think I know why: the modifiers' names get duplicated.

**Comment by Kasualix** [comment]
I suppose you could use different names in the json (e.g., for reinforced, you could try reinforced_curios, reinforced_armor, and reinforced_shield), but still translate them to the same name in the resourcepack made for display

**Comment by Kasualix** [comment]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/5b14dd93-ad2f-4ee3-b7b9-95107a369ced)
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/21d661f2-cf7f-4ecd-b2a5-bccfd0479feb)
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/edbbb8ed-53d9-4adf-801e-f958c77673e3)

hmm, this setup works well for me. Do you have the WhetherOrNotCuriosUseArmorModifiers option disabled in curios-modifiers.toml? It is enabled by default

**Comment by Kasualix** [comment]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/e2d62733-c3e2-46a5-b54f-6470783b849c)
Well I was wrong, duplicate names works fine too

**Comment by Kasualix** [comment]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/8eb44bf8-3616-4c96-8535-084cea8cf8e9)
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/2e1096d3-c0e9-4148-9384-bffe694f4790)

I added some more jsons and it works too.
The version I'm using:
[unzip me.zip](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/14142126/unzip.me.zip)

**Comment by Kasualix** [comment]
Odd, I didn't set a limit

**Comment by Kasualix** [comment]
supposed:

**Comment by Kasualix** [comment]
so do these two
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/35d05e48-b98f-4597-80e8-0c8cfd605ab1)

**Comment by Kasualix** [comment]
Should I crash the game if one config has errors?

**Comment by Kasualix** [comment]
A config option has been added to allow crash on config errors in the version I released last night (enabled by default), thanks for your report anyway.
