### ISSUE TITLE
Question: Do you make any AI changes to bees?

### ISSUE THREAD

**Issue by Cixon** [MCTeamPotato/Kasualix-Issue-Tracker#12]
title.

reason:
![Screenshot (51)](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/69068153/6503a540-9242-44e1-a959-2db33ad491cc)

**Comment by Kasualix** [comment]
There is global issue tracker. I can't find any mods that have been mentioned in all the minor details

**Comment by Cixon** [comment]
> There is global issue tracker. I can't find any mods that have been mentioned in all the minor details.
> Bee Fix mod would help but mojang's stupid animals can still be laggy due to the slow pathfinding tbh

I think the bee fix mod will work. Didn’t know there were a on-going TPS bug. Glad that mod fixes it!
