### ISSUE TITLE
[DoesPotatoTick] - Crashing with ponder of Create

### ISSUE THREAD

**Issue by supernova0102** [MCTeamPotato/Kasualix-Issue-Tracker#120]
### Specific mod for which you open this issue

DoesPotatotick

### MC version & mod version

mc1.19.2, DPt 4.0.1

### Latest log

https://gist.github.com/supernova0102/b70a16a20af3773f94345829d4c2839a

### Issue description

Crash with Ponder feature of Create

when i ponder item, DoesPotatoTick make a Crash

**Comment by OracleHisty** [comment]
This is still relevant in the current version of 1.20.1. >Bump

Please make note in curseforge that ponder breaks with this mod installed.
