### ISSUE TITLE
Sparse Structures Reforged: Incorrectly tagged as "Client: Unsupported" on Modrinth

### ISSUE THREAD

**Issue by gardenappl** [MCTeamPotato/Kasualix-Issue-Tracker#121]
### Specific mod for which you open this issue

Sparse Structures Reforged

### MC version & mod version

N/A

### Issue description

It should be tagged as "Client: Optional" instead, since it does not break clients, and in fact should be installed on clients if they play singleplayer.

Right now tools like [packwiz](https://packwiz.infra.link/) interpret this as saying "this mod breaks clients", so they only install it on dedicated servers.

**Comment by Kasualix** [comment]
updated
