### ISSUE TITLE
Crash on startup with BadOptimizations

### ISSUE THREAD

**Issue by border999** [MCTeamPotato/Kasualix-Issue-Tracker#122]
### Specific mod for which you open this issue

Redirector

### MC version & mod version

1.20.1 redirector-5.0.0

### Latest log

https://gist.github.com/border999/ad255c7f74b7f7f96f8efa65c63a2a6f

### Issue description

looks like this mod and BadOptimizations are tripping over each other on startup.

**Comment by border999** [comment]
https://github.com/ItsThosea/BadOptimizations/issues/36

**Comment by Kasualix** [comment]
https://github.com/ItsThosea/BadOptimizations/issues/36#issuecomment-1944484833
