### ISSUE TITLE
Feature Request - Hoglins also immune to fire/lava

### ISSUE THREAD

**Issue by anoomolu** [MCTeamPotato/Kasualix-Issue-Tracker#123]
### Specific mod for which you open this issue

PiglinSafety

### MC version & mod version

1.16.5-0.1.0

### Issue description

Hiya, firstly thank you for still supporting 1.16. I really appreciate it <3

Would it be possible to expand the mod to Hoglins as well? Their zombie form is already fire-immune, so it makes sense to me.

Thanks for your time!

**Comment by Kasualix** [comment]
Added in 1.0.0
