### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by benio1394** [MCTeamPotato/Kasualix-Issue-Tracker#126]
### Specific mod for which you open this issue

Modern Inhibited

### MC version & mod version

1.20.1, 1.0.5

### Issue description

Game crash on start without crash log on the newest fabric version

**Comment by Kasualix** [comment]
The latest 1201 fabric is 1.1.0, I'll correct the release tag https://legacy.curseforge.com/minecraft/mc-mods/modern-inhibited/files/4872039
