### ISSUE TITLE
EnchantDemon crash on game startup. "UnsupportedClassVersionError"

### ISSUE THREAD

**Issue by maxim0p** [MCTeamPotato/Kasualix-Issue-Tracker#129]
### Specific mod for which you open this issue

EnchantDemon

### MC version & mod version & loader version

1.16.5 - Forge version 36.2.41 - enchantdemon-1.16.5-0.0.1.jar

### Latest log

https://pastebin.com/r0GPgDaE

### Issue description

EnchantDemon crashes when starting up the game.
Checking the logs it says it is caused by 
`Caused by: java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: net/minecraft/enchantment/Enchantment has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

Any possibility to get a quick fix / a version not requiring newer Java versions? I desperately need a simple mod that disables enchants for my modpack, and I don't want to make using newer Java versions a requirement. Thanks.

**Comment by Kasualix** [comment]
fixed in 0.0.2
