### ISSUE TITLE
Dimensional Threading and Redirectionor conflict

### ISSUE THREAD

**Issue by Atmxsz** [MCTeamPotato/Kasualix-Issue-Tracker#14]
### Mod Loader
Forge 43.2.21

### Minecraft Version
1.19.2

### Mod Version
3.0.2

### Notes
Note: Conflict with Dimensional Threading. I am reporting this problem to the developers of both mods.

### Steps
Run Minecraft.
Exit with code 2.
There is no crash report.

### Latest Log
[Latest](https://hst.sh/ayoxaserop)

**Comment by Kasualix** [comment]
Now you can close [the other side](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/issues/9)

**Comment by Kasualix** [comment]
1.18.2 and 1.16.5 will contain this patch tomorrow too, now I'm going to bed.
