### ISSUE TITLE
Add a config to allow entity to despawn when not ticking

### ISSUE THREAD

**Issue by Xiarno** [MCTeamPotato/Kasualix-Issue-Tracker#15]
It seems that, from my research, while the entities are in a state of "not ticking", they are unable to despawn. Eventually filling the mob cap and not allowing any other to spawn.

In my opinion, I think that adding an option to allow the entities to despawn would fix or at least help the issue.

**Comment by Kasualix** [comment]
You are using adaptive performance tweaks?

**Comment by Kasualix** [comment]
by default, stopping ticking is not conflict with despawing unless you are using adaptive performance tweaks spawn optimization. In the old issues of DPT, this kind of issues had appeared and end with declaring the incompatibility with adaptive performance tweaks.
