### ISSUE TITLE
用opotato配置灾变部分数值后，烈焰轰击导致游戏崩溃

### ISSUE THREAD

**Issue by A0000Xz** [MCTeamPotato/Kasualix-Issue-Tracker#16]
由于都会中国话我就不说英语了。
在崩溃后我重启了好几次，当时是用的java17（配合modernfix改参数）
我想会不会是java11就没事了，结果进去还是崩。存档已经放出来烈焰轰击了，每次一进去就崩。
之后我把opotato的配置文件和模组本体删了才不崩。
[crash-2023-07-24_18.37.17-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12156444/crash-2023-07-24_18.37.17-server.txt)
[crash-2023-07-24_18.35.05-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12156450/crash-2023-07-24_18.35.05-server.txt)
这是两个相关的崩溃报告
话说我看到一个炎葬充能的配置数值居然是72000刻，那是焰魔开大的时间嘛？可我寻思焰魔开大CD也没这么长吧。那是干什么的

**Comment by Kasualix** [comment]
试试1.15.2？

**Comment by Kasualix** [comment]
Will be fixed in 2.0.0
