### ISSUE TITLE
用remodfier写出新词条后在游戏内崩溃

### ISSUE THREAD

**Issue by A0000Xz** [MCTeamPotato/Kasualix-Issue-Tracker#18]
我还是只打中文吧。
用remodfier写出新词条后，启动成功，但是在游戏里只是把鼠标放创造模式栏里刚写出的新词缀书上就崩溃了。
我也不知道为什么，这是崩溃日志：
[crash-2023-07-27_21.17.15-client.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12183911/crash-2023-07-27_21.17.15-client.txt)
为什么我每次试图用土豆给的模组想要整些活的时候就给我崩溃啊。。。。。。
[remodifier-tool-modifiers.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12183928/remodifier-tool-modifiers.txt)
这是我写的新词缀的配置文件，搞不懂啊，应该没毛病啊，为什么会崩。
虽然我是给一个武器写上了手持时加防御什么的，但这本书我甚至都没翻到啊，我翻得是另一本很正常比着原有词缀写的啊。
我不知道remodfier的issue是不是该写这里，但我实在是找不到别的issue啊。

**Comment by A0000Xz** [comment]
补充一点，我其实是在写以灾变在1.16的三个BOSS为名的强化词缀，结果我发现除了末影守卫那个书没问题，其他的书只要试图获得或者看一眼就崩溃，难不成是数值有限度，我写太多了？

**Comment by Kasualix** [comment]
刚更了一下，再试试？
