### ISSUE TITLE
Crashes when used with Lanterns Belong on Walls

### ISSUE THREAD

**Issue by Rad233** [MCTeamPotato/Kasualix-Issue-Tracker#19]
Version: 1.18.2 fabric+redirectionor 2.0.3
Lanterns Belong on Walls: [https://github.com/ThePoultryMan/Lanterns-Belong-On-Walls](url)
Log:
[2023-08-01-5.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12229162/2023-08-01-5.txt)

**Comment by Kasualix** [comment]
Duplicate with #8, will be resolved in the next re-write release.

**Comment by Kasualix** [comment]
will be resolved in the next re-write release
