### ISSUE TITLE
Can't be recognized as a mod

### ISSUE THREAD

**Issue by Rad233** [MCTeamPotato/Kasualix-Issue-Tracker#21]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/99306685/ccb75902-73a2-49a9-bb9b-694ac2d3e066)

**Comment by Kasualix** [comment]
which mod?

**Comment by Rad233** [comment]
> 

redirectionor

**Comment by Kasualix** [comment]
Oh, I just found it

**Comment by Kasualix** [comment]
Reuploaded
