### ISSUE TITLE
Redirectionor 2.1.0 conflicts with NicerPortals

### ISSUE THREAD

**Issue by Rad233** [MCTeamPotato/Kasualix-Issue-Tracker#22]
Game crashes using these two mods together.
https://modrinth.com/mod/nicer-portals
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12262205/latest.log)

**Comment by Kasualix** [comment]
可你的日志并没有有效的报错，看起来更像是被手动中断的（？）

**Comment by Rad233** [comment]
> 可你的日志并没有有效的报错嘛，而且redirectionor的mixin优先级比别的模组都低，如果别的模组先改过了，redirectionor的mixin应该是会直接被跳过的

抱歉，上传错了

**Comment by SiverDX** [comment]
https://github.com/MCTeamPotato/Redirectionor/blob/1.19.2/common/src/main/java/com/teampotato/redirectionor/mixin/world/level/block/BaseFireBlockMixin.java

vs

https://github.com/Roundaround/mc-fabric-nicer-portals/blob/main/src/main/java/me/roundaround/nicerportals/mixin/AbstractFireBlockMixin.java

guess priority (for redirect?) doesn't work with some? other type of mixins

**Comment by Kasualix** [comment]
> https://github.com/MCTeamPotato/Redirectionor/blob/1.19.2/common/src/main/java/com/teampotato/redirectionor/mixin/world/level/block/BaseFireBlockMixin.java
> 
> vs
> 
> https://github.com/Roundaround/mc-fabric-nicer-portals/blob/main/src/main/java/me/roundaround/nicerportals/mixin/AbstractFireBlockMixin.java
> 
> guess priority (for redirect?) doesn't work with some? other type of mixins

ModifyVariable is not working with Redirect
I will add config option like sodium/lithium and disable the BaseFireBlockMixin when nicer portal is present.
