### ISSUE TITLE
1.19.2 Crash (RecipeBookSettings)

### ISSUE THREAD

**Issue by tharrmeehan** [MCTeamPotato/Kasualix-Issue-Tracker#24]
Hello.

Using the latest version of your mod redirectionor-1.19.2-3.2.1-forge.jar causes my game to crash. Downgrading to an older version fixes this.

Thanks for your help.

[crash-2023-08-06_10.56.42-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12269052/crash-2023-08-06_10.56.42-server.txt)

**Comment by Kasualix** [comment]
adding 'mixin.stats=false' to the mixin config is a temporary fix

**Comment by tharrmeehan** [comment]
There does not seem to be a mixin config file for your mod in my instance. Is it named in a specific way? Because searching mixin or redirectionor does not seem to yield any results.

**Comment by Kasualix** [comment]
redirectionor-mixins.properties
in .minecraft/versions/[Modpack Name]/config/

**Comment by tharrmeehan** [comment]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/58373200/b05e889a-fb60-47f4-8941-5b58b726f90f)

![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/58373200/a6e79e6a-5e87-4712-a68a-2edced44c62b)

Hmmm, can't seem to find it. It does not create one even if the mod is installed alone or if i reset my config folder. I do not use a modpack by the way if that makes any difference (probably not)
