### ISSUE TITLE
1.18.2 - Goal Optimizer "Failed to start server"

### ISSUE THREAD

**Issue by Aarods** [MCTeamPotato/Kasualix-Issue-Tracker#25]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110215990/72688271-bf8f-415b-8edd-9f4a67356ec3)
When starting the server with GoalOptimizer in its latest version, the server doesn't start and reports an error.

Logs: 
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12270200/latest.log)

**Comment by Kasualix** [comment]
Fixed in 1.1.2 

https://legacy.curseforge.com/minecraft/mc-mods/goal-optimizer/files/4686513
