### ISSUE TITLE
Goal Optimizer, Roadrunner 

### ISSUE THREAD

**Issue by WolfBV** [MCTeamPotato/Kasualix-Issue-Tracker#26]
In the curseforge description of Goal Optimizer "If you install RoadRunner, the second tweak will be automatically disabled as RoadRunner contains some part of this optimization, but I would not recommend using it, see [here](https://github.com/MCTeamPotato/Redirectionor/issues/1#issuecomment-1604455552)"

The explanation for why Roadrunner's optimization shouldn't be used links to a 404 github page, what was the explanation?

**Comment by Kasualix** [comment]
The issue was accidentally deleted, here Iet me explain again.

When I removed RoadRunner from my pack, my FPS: 400 → 500, that's it.

This is my own situation, you can go ahead using it if you don't this situation.
