### ISSUE TITLE
Crash remodifier-1.19.2-2.0.0

### ISSUE THREAD

**Issue by Ashuntoi** [MCTeamPotato/Kasualix-Issue-Tracker#27]
Hello, 

I have a issue with your mod remodifier-1.19.2-2.0.0, when i first launch minecraft with your mod it's work but after that it's keep crashing.

i think the issue come from your config files remodifier-reforge.toml.
The config files are fresh new i delete the old for the new to generate i put the crash log on attach files.
[crash-2023-08-11_12.39.57-client.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12320685/crash-2023-08-11_12.39.57-client.txt)

**Comment by Kasualix** [comment]
Fixed in https://legacy.curseforge.com/minecraft/mc-mods/remodified/files/4695647
currently under review
