### ISSUE TITLE
[1.18.2] [Mod-Comp] Sky mixin error with Rubidium 

### ISSUE THREAD

**Issue by Cixon** [MCTeamPotato/Kasualix-Issue-Tracker#3]
Log (ln 1,641):
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/11996563/latest.log)

Crash (recieved from loading sp world):
[crash-2023-07-09_18.54.43-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/11996575/crash-2023-07-09_18.54.43-server.txt)

Addition Context:
A mod called Nostalgic tweaks received a update recently that overrides the cloud and sky behavior from rubidium. It might be too much mixin overrides for Redirectionor to keep up so I'll send that commit below incase you need it.

Commit:
https://github.com/Adrenix/Nostalgic-Tweaks/commit/538ef38b06ad21ab94d0b67dd170ef3bbc35a126

**Comment by Kasualix** [comment]
Phosphor does the same thing as Redirectionor, causes incompatibility.
Why not starlight? Isn't it excellent? Even merged into vanilla by mojang in 1.20.

**Comment by Cixon** [comment]
Starlight incompat with my 1.18 modpack.

So I use this instead:
https://www.curseforge.com/minecraft/mc-mods/radon

**Comment by Cixon** [comment]
Also, I did not know this.... lul

**Comment by Kasualix** [comment]
I'll ensure phosphor compatibility in the next version.

**Comment by Cixon** [comment]
> Phosphor does the same thing as Redirectionor, causes incompatibility. Why not starlight? Isn't it excellent? Even merged into vanilla by mojang in 1.20.

If Radon does the same thing, would it be more performant to just remove Radon or allow Radon?
I'm confused.... 😅

**Comment by Cixon** [comment]
I guess you'll need to undergo some testing to see what performs better overall. A patch for radon or just remove it

**Comment by Kasualix** [comment]
Phosphor (or Radon) and Redirectionor both remove the direction allocation in the SkyLightEngine class. I mean this by "doea the same thing"

**Comment by Kasualix** [comment]
fixed in 2.0.1

**Comment by Cixon** [comment]
Thank you!
