### ISSUE TITLE
opotato and headshot crash

### ISSUE THREAD

**Issue by J-Kikutaro** [MCTeamPotato/Kasualix-Issue-Tracker#30]
Installing opotato-1.16.5-1.15.2 and headshot-1.3.0 crashes.
From the crash report, it appears that headshot-1.3.0 is failing to load.

[crash-2023-08-10_20.10.59-fml.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12386229/crash-2023-08-10_20.10.59-fml.txt)

**Comment by Kasualix** [comment]
should be fixed in 1.15.3
