### ISSUE TITLE
Blacklist request for KeepCuriosInventory

### ISSUE THREAD

**Issue by Inf0214** [MCTeamPotato/Kasualix-Issue-Tracker#32]
Would be nice to have a blacklist option so things like backpacks can still be droped.

**Comment by Inf0214** [comment]
What is despawn tweaker? Sorry if I wasnt explaining correctly, I want to keep the CuriosInventory but still drop the backpack from a backpack mod I use since it can hold a bunch of stuff.

**Comment by Kasualix** [comment]
uploaded
