### ISSUE TITLE
[Enhancement] DoesPotatoTick Fabric Version for 1.20.1

### ISSUE THREAD

**Issue by DeshiDesu** [MCTeamPotato/Kasualix-Issue-Tracker#33]
As much as I want the fabric version, it all depends on author's end to decide.

I understand if there is a reason, but we would like to know what it is.

**Comment by Kasualix** [comment]
which mod?

**Comment by DeshiDesu** [comment]
> which mod?

DoesPotatoTick

**Comment by DeshiDesu** [comment]
I apologize for not mentioning which mod, but I am still waiting for an answer.

**Comment by Kasualix** [comment]
Currently I'm on my way home from a trip by train, I'll do it when I get home.

**Comment by DeshiDesu** [comment]
thank you

**Comment by Kasualix** [comment]
uploaded

**Comment by DeshiDesu** [comment]
thanks ill check it out
