### ISSUE TITLE
Custom modifier crashes and bugs in remodifier-1.16.5-2.0.1

### ISSUE THREAD

**Issue by J-Kikutaro** [MCTeamPotato/Kasualix-Issue-Tracker#35]
I added a new modifier "eternal" to armor-n-curio-modifiers and when I tried to check its effect, the GUI displayed something like the screenshot. If you hover the mouse cursor over the armor icon, it crashes.
Here is the crash report, the toml file used and the screenshot.
[crash-2023-08-18_23.20.53-client.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12445012/crash-2023-08-18_23.20.53-client.txt)
[armor-n-curio-modifiers.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12445014/armor-n-curio-modifiers.txt)
![2023-08-18_23 13 44](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/142008350/46495d0f-de4c-44a6-bf3f-95ccde09aa2a)
I then added a new modifier "zantetsu" to the tool-modifiers file and added it to the iron sword, and the crash did not occur when I hovered the mouse cursor over it. However, as you can see in the screenshot, the sword with the "zantetsu" modifier is not displayed when held in the hand, while the sword with the default modifier is displayed without any problem. I also added +50% movement speed to Legendary, which works fine with the added effect without crashing.
[tool-modifiers.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12445018/tool-modifiers.txt)
![2023-08-18_23 12 03](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/142008350/8261ff14-e9f6-4f5f-b742-57a550c6f085)
![2023-08-18_23 12 44](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/142008350/d82d414f-123b-4571-a92a-e9208bd7ec09)
![2023-08-18_23 12 42](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/142008350/1516aaf8-1f04-4330-b1f2-5a11049e891a)

In addition, after rewriting the default "guarding" to the aforementioned "eternal", a crash occurs when the mouse cursor is hovered over a leather jacket, and a crash also occurs when the jacket is worn by right-clicking from the hotbar.
The following is the configuration file and crash report.
[armor-n-curio-modifiers.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12445019/armor-n-curio-modifiers.txt)
[crash-2023-08-18_22.44.11-client.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12445043/crash-2023-08-18_22.44.11-client.txt)
[crash-2023-08-18_22.45.07-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12445044/crash-2023-08-18_22.45.07-server.txt)

**Comment by Kasualix** [comment]
you need to define translation keys and values for your Modifier by custom resourcepack, or the game will crash.
See https://github.com/MCTeamPotato/Remodifier/blob/5a0568088c8fcb0611af693ad4e69c68ce5150f3/src/main/java/com/teampotato/modifiers/common/config/CurioNArmorConfig.java#L19, also available in config/remodifier/armor-n-curio-modifiers.toml config desc.
