### ISSUE TITLE
[AnimaticaReforged] Wrong forge version for 1.18.2

### ISSUE THREAD

**Issue by Starexify** [MCTeamPotato/Kasualix-Issue-Tracker#36]
Mod Version> 1.18.2-0.0.2
Forge Version> 1.18.2 - Forge - 40.2.10
Issue> The 1.18.2-0.0.2 version requires fml:43 which is 1.19+ but the version should be fml:40 for 1.18.2.

[Image to see the problem](https://imgur.com/n2RtChz)

How to solve this if you get it: Downgrade to 1.18.2-0.0.1 version of AnimaticaReforged

Please solve this issue because I see the update button and its confusing xD

**Comment by Kasualix** [comment]
XD
