### ISSUE TITLE
crash with animatica as soon as a resource pack is loaded

### ISSUE THREAD

**Issue by Aer-ink** [MCTeamPotato/Kasualix-Issue-Tracker#37]
forge: 40.2.10
minecraft: 1.18.2
animatica: 1.18.2-0.0.2-

it seems like the game will crash as soon as "BOTW GUI" resource pack is loaded no other mods loaded 

crash log:
https://paste.ee/p/U6daK

**Comment by Kasualix** [comment]
It's fixed, but do note that Animatica has very severe performance issue on rendering high resolution textures, see https://github.com/FoundationGames/Animatica/issues/43, which would lead to huge lag.
