### ISSUE TITLE
 ForgeSkyboxes 1.18崩溃

### ISSUE THREAD

**Issue by supershorty1** [MCTeamPotato/Kasualix-Issue-Tracker#40]
[crash-2023-08-28_10.24.43-fml.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12449702/crash-2023-08-28_10.24.43-fml.txt)

**Comment by Kasualix** [comment]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/8183f750-70f0-4045-85d5-32ae261e9bc3)
