### ISSUE TITLE
[Papi] Incompatible with Fabric Biome API Reforged

### ISSUE THREAD

**Issue by supershorty1** [MCTeamPotato/Kasualix-Issue-Tracker#41]
[游戏崩溃前的输出.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12449823/default.txt)
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12449824/latest.log)
[debug.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12449826/debug.log)

**Comment by Kasualix** [comment]
papi 跟 fabric biome api reforged，二选一。

**Comment by Kasualix** [comment]
papi 未来会包含 fabric biome api reforged 的全部功能，在此之前，此 issue 保持开放。

**Comment by Kasualix** [comment]
算了，还是乖乖改包名吧，要兼容余烬奇景它们还得专分出来一个fabric-biome-api的modID，太麻烦了
