### ISSUE TITLE
1.12.2的1.8.8崩溃

### ISSUE THREAD

**Issue by MPCQUQ666** [MCTeamPotato/Kasualix-Issue-Tracker#43]
[crash-2023-08-28_18.17.18-client.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12453367/crash-2023-08-28_18.17.18-client.txt)

**Comment by Kasualix** [comment]
已分离，我这不再收1122的issue

**Comment by Ecdcaeb** [comment]
很奇怪
刚才那个暮色森林也是出现了Anonymous这个奇怪的不存在类。
#42 https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/issues/42

**Comment by Ecdcaeb** [comment]
@MPCQUQ666

**Comment by Ecdcaeb** [comment]
测试JEI也是正常
怪

**Comment by MPCQUQ666** [comment]
不是

**Comment by Ecdcaeb** [comment]
使用新版本能够解决问题吗？

**Comment by MPCQUQ666** [comment]
最新版不就是1.8.8吗？

**Comment by Ecdcaeb** [comment]
这是指mc版本使用范围，1.12.2-1.8.8，我后来覆盖了一次

**Comment by MPCQUQ666** [comment]
感谢，不会崩溃了
