### ISSUE TITLE
[1.20.1] Redirectionor模组与莱特兰部分模组不兼容

### ISSUE THREAD

**Issue by Dr-WeiAL** [MCTeamPotato/Kasualix-Issue-Tracker#44]
经过实测，与莱特兰的[弓艺](https://www.mcmod.cn/class/8802.html)，[扩充](https://www.mcmod.cn/class/8797.html)，[武器](https://www.mcmod.cn/class/9873.html)不兼容，向对方反馈后来到这里进行反馈
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/47446553/4fa356cb-3d55-4281-adcc-2419bfa60697)
[crash-2023-08-28_18.30.26-fml.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12453454/crash-2023-08-28_18.30.26-fml.txt)

补充：虽然移除了这三个模组后可以启动游戏，但进入世界仍然会崩溃，与莱特兰其他模组也不兼容(
再补充：将莱特兰全部模组移除掉后也无法进入世界，虽然不会崩溃，但会卡在加载地形中

**Comment by Kasualix** [comment]
怪了，试试这个https://filebin.net/949jo76uoqtnt272？

**Comment by Dr-WeiAL** [comment]
> 怪了，试试这个？https://filebin.net/949jo76uoqtnt272

这个可以用，不会出现上述的问题了

**Comment by Kasualix** [comment]
ok，待会儿发新版本

**Comment by Dr-WeiAL** [comment]
> ok，待会儿发新版本

不对，你刚刚发的模组是空文件

**Comment by Kasualix** [comment]
草，idea又抽风了

**Comment by Kasualix** [comment]
https://filebin.net/kz4zf3bhaja9dqg9这回不是了

**Comment by Dr-WeiAL** [comment]
> https://filebin.net/kz4zf3bhaja9dqg9 这回不是了

还是有问题
[crash-2023-08-28_19.04.52-fml.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12453706/crash-2023-08-28_19.04.52-fml.txt)

**Comment by Kasualix** [comment]
[解压我.zip](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12453733/default.zip)
这个应该大概可能也许就没问题了

**Comment by Dr-WeiAL** [comment]
> [解压我.zip](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12453733/default.zip) 这个应该大概可能也许就没问题了

这次确实没问题了(
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/47446553/53909d55-7cea-47a5-8aea-7fd60e8f2cac)
