### ISSUE TITLE
Crash with Redirectionor 

### ISSUE THREAD

**Issue by Aarods** [MCTeamPotato/Kasualix-Issue-Tracker#45]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110215990/7c5464fa-6ffd-422d-8783-0edf4951d72d)

When starting the server with Redirectionor (1.5.1 - 1.16.5, I don't know if this happens with other versions yet.) the server crashes at startup.
Logs:
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12454344/latest.log)

**Comment by Kasualix** [comment]
Can you try this build? https://filebin.net/sqebq89rrriehbln

**Comment by Kasualix** [comment]
I tested and resolved another ChatFormatting mixin log warning, thanks to your report, I'll create a new release
