### ISSUE TITLE
[Forge Skyboxes 1.20.1] Game unable to launch

### ISSUE THREAD

**Issue by moninformateur** [MCTeamPotato/Kasualix-Issue-Tracker#46]
[Here's the crash log on mclo.gs](https://mclo.gs/3XCHaPp). 

I am unsure what is causing the game not to launch. All three mods related to Forge Skyboxes are enabled. Any clue?

**Comment by Kasualix** [comment]
forgeskyboxes 1.20.1 requires forgified fabric api

**Comment by moninformateur** [comment]
But I do have it installed... What am I doing wrong?

![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/79221061/49d3c3fd-0c1b-4718-875b-430fd4cf02fa)
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/79221061/9b253533-5f92-4554-89d0-71f643eef957)

**Comment by Kasualix** [comment]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/f919e79d-bf95-47d0-8f47-97657183ce5b)
In the log you gave, it's not installed

**Comment by Kasualix** [comment]
Can I take a look at your full log?

**Comment by moninformateur** [comment]
Sure, [here's the full lastest log.](https://mclo.gs/MBQzv0K)

**Comment by Kasualix** [comment]
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/fca8e066-c694-4aa7-9208-1d5be356f6bc)
That's odd, the part of Fabric API that includes the missing class should have been successfully loaded into the game.
I'm not sure why either, and my test was able to successfully start and load Dramatic Skys as well.
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/ece4eeb0-323f-4e0e-9a24-31b313f32467)
![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/aa7be26f-9a72-46de-a746-251f12471b72)

**Comment by moninformateur** [comment]
That's weird. I suspect there may be a mod somewhere that interfere. I will report back if I find which one it is.

**Comment by moninformateur** [comment]
The problem is with the [Let's do Meadow mod](https://www.curseforge.com/minecraft/mc-mods/welcome-to-meadow).

Opened an issue on their Discord.
