### ISSUE TITLE
异引定址与 AE2 Unoffical Extended Life 安装时冲突。

### ISSUE THREAD

**Issue by KasumiNova** [MCTeamPotato/Kasualix-Issue-Tracker#48]
异引定址版本：1.12.2-1.8.8-1.1
相关日志：https://mclo.gs/vNSADjW

**Comment by Kasualix** [comment]
我这不收1122的，去helib那里（
https://github.com/Ecdcaeb/Redirectionor/issues

**Comment by Kasualix** [comment]
而且好像有人报过了https://github.com/Ecdcaeb/Redirectionor/issues/3
