### ISSUE TITLE
papi与方块小镇的兼容性问题

### ISSUE THREAD

**Issue by Miaochan** [MCTeamPotato/Kasualix-Issue-Tracker#49]
当papi与[方块小镇](https://www.curseforge.com/minecraft/mc-mods/yuushya-townscape)同时安装时，将方块小镇的头戴装饰拖动到头部装备栏后游戏会发生崩溃
我向方块小镇团队反馈此问题时他们表示崩溃的原因是头戴装饰同时触发了papi和architectury的方法，并让我来此询问使papi兼容architectury的办法
崩溃日志附上:
[crash-2023-09-01_13.53.19-client.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12504229/crash-2023-09-01_13.53.19-client.txt)
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12504230/latest.log)

测试版本：1.19.2
mod列表:architectury-6.5.85-forge 
papi-1.19.2-1.0.0
yuushya-1.19.2-forge-2.0.0
yuushya-modelling-1.19.2-forge-2.0.0

**Comment by Kasualix** [comment]
1.0.1，经过测试应该没问题了，可以正常戴上圣诞帽
