### ISSUE TITLE
Incompatibility with Canary

### ISSUE THREAD

**Issue by zalfrost** [MCTeamPotato/Kasualix-Issue-Tracker#5]
I just wanted to tell you guys that this mod is not compatible with [Canary](https://www.curseforge.com/minecraft/mc-mods/canary) since Canary has a conflicted feature with this mod. Both features did the same thing so Minecraft didn't know which to choose and just force closed. 

Here is the [log file](https://pastebin.com/8qBRR8bi).

**Comment by Kasualix** [comment]
Strange, I have worked on the canary compatibility one week ago in LPS's modpacks, but I'll make it compatible again.
Anyway, Lithium forge ports are buggy and unstable, I don't recommend using them at all.
