### ISSUE TITLE
Redirectionor进入世界时崩溃

### ISSUE THREAD

**Issue by Le7emps** [MCTeamPotato/Kasualix-Issue-Tracker#50]
[crash-2023-09-03_02.06.10-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12504493/crash-2023-09-03_02.06.10-server.txt)（客户端崩溃报告）

[crash-2023-09-03_01.51.37-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12504497/crash-2023-09-03_01.51.37-server.txt)（服务端崩溃报告）

**Comment by Kasualix** [comment]
https://filebin.net/24e0jg254imrqai7
试试这个？

**Comment by Kasualix** [comment]
@Le7emps ?

**Comment by Kasualix** [comment]
方便发下包吗，蓝奏云/百度网盘啥的，另外我前天电脑键盘坏了在拿去修，可能得过个两三天送回来了才能解决（

**Comment by Le7emps** [comment]
链接：https://pan.baidu.com/s/1An4p-pFLWKOr7WnuJfdgXA?pwd=1234 
提取码：1234 
--来自百度网盘超级会员V7的分享
