### ISSUE TITLE
Server Crash With DoesPotatoTick? 1.20.1

### ISSUE THREAD

**Issue by Devilswarchild** [MCTeamPotato/Kasualix-Issue-Tracker#51]
MC: 1.20.1
Forge: 47.1.3
Mod Version : does_potato_tick-1.20.1-3.6.1

Crash Report for Easy Reading: https://mclo.gs/rJJzkbx

crashes the server during startup

**Comment by SiverDX** [comment]
https://github.com/FTBTeam/FTB-Chunks/commit/e376d77e2b4f470dd38a6136eeb008b01cd3d736 API got moved

Latest version you can use at the moment is https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/4597016

**Comment by Kasualix** [comment]
I have already known, but 
![IMG_20230906_221119](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/110756250/f7710d88-7f18-43e3-a6fd-8f57d8a0edc4)

**Comment by SiverDX** [comment]
versions after 1.2 will crash due to the change mentioned above
