### ISSUE TITLE
(DoesPotatoTick) Possible Crash with Cataclysm

### ISSUE THREAD

**Issue by Aarods** [MCTeamPotato/Kasualix-Issue-Tracker#56]
I'm not sure at all if this is fully related to this, but when I tried to use Cataclysm (Last version of 1.16) but when I use "The Incinerator" it summons some runes in the floor, when it targets something it crashes the server, but when is use without a target, it works as usually. (As I said, I'm not sure at all if this mod is really the cause but the crash report says something related to this.)

Version: 1.16.5

[crash-2023-09-09_17.10.50-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12566367/crash-2023-09-09_17.10.50-server.txt)

**Comment by Kasualix** [comment]
Oh, It's Opotato's bug, currently I am re-writing it for better codes structure and more contents, 2.0.0 will be released in a few days, which will fix this hopefully

**Comment by Kasualix** [comment]
2.0.0 released
