### ISSUE TITLE
[1.20.1] Potatweaker - Doesn't remove iron golems from villages

### ISSUE THREAD

**Issue by Cixon** [MCTeamPotato/Kasualix-Issue-Tracker#67]
Using the same config from ticket #66 ;

The village golem still exists, perhaps there can be an additional config that allows users to dictate rather or not this also affects player-created golems too.

_(i only want to remove village golems)_

**Comment by Kasualix** [comment]
I'll change how potatweaker works in the next version to match your requirement.

**Comment by Cixon** [comment]
oh I see. this is why structural entities still exist… i’d really appreciate if you could fix it, thanks!

**Comment by Kasualix** [comment]
Should be fixed in 1.1.1
