### ISSUE TITLE
[1.20.1] Potatweaker - EntityJoinLevelEvent deletes base NBT data.

### ISSUE THREAD

**Issue by Cixon** [MCTeamPotato/Kasualix-Issue-Tracker#68]
In previous config, the piglins that replace the EntityJoinLevelEvent villagers no longer carry their main hand weapons such as crossbow and golden sword. I wish to see this fixed, thank you for the bug fixing! :-)

**Comment by Kasualix** [comment]
The nbt list is left empty, which makes the summoned entities will not have any nbt including weapon in hand. 
I'll add one more config option to define whether or not to use nbt list.

**Comment by Kasualix** [comment]
1.1.2 uploaded
