### ISSUE TITLE
Crash Stark (1.16)

### ISSUE THREAD

**Issue by Aarods** [MCTeamPotato/Kasualix-Issue-Tracker#7]
It's nothing new really, I encountered this error before but the crash didn't register it and it's occasional when this error appears, I don't even know the conditions. The server crashes at a random time with a report from Stark. (I'm not entirely sure if stark is the cause).
[crash-2023-07-12_02.00.42-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12027296/crash-2023-07-12_02.00.42-server.txt)

**Comment by Kasualix** [comment]
I'm not entirely sure if stark is the cause too.
Can you try to temporarily remove dungeons libraries and its addon?

**Comment by Aarods** [comment]
Sure, but the thing is to replicate the bug, this only happened twice at unexpected times, with no conditions that I have seen. So it is difficult to repeat it again.

**Comment by Kasualix** [comment]
Maybe I can only remove the isAllowedOnBooks configuration option.

**Comment by Kasualix** [comment]
Oh, I found the problem, I didn't build this config option so it's null.
Should be resolved now
