### ISSUE TITLE
[Help Wanted] Can you add a guide to replace villager profressions?

### ISSUE THREAD

**Issue by Cixon** [MCTeamPotato/Kasualix-Issue-Tracker#70]
Hello! I know there's a NBT replacer thingy but I have no clue if I'd be able to use it to specify a profession.
I really love this mod so far, great work!

**Comment by Kasualix** [comment]
Try Property Modifier mod?

**Comment by Kasualix** [comment]
@Cixon Can this work?

**Comment by Cixon** [comment]
I will test!
