### ISSUE TITLE
[Question] Is MCretector compatible w ModSets (putting mods in subfolders)

### ISSUE THREAD

**Issue by MrKashew** [MCTeamPotato/Kasualix-Issue-Tracker#71]
Have yet to try together but this is the mod:
https://modrinth.com/mod/mod-sets/versions?l=forge

**Comment by Kasualix** [comment]
I haven't tried yet and I _think_ it would work

**Comment by Kasualix** [comment]
Tested with another mod based on Forge's Locator service (same principle as mod sets) and it works well
