### ISSUE TITLE
Opatato对灾变的额外配置出了些问题

### ISSUE THREAD

**Issue by A0000Xz** [MCTeamPotato/Kasualix-Issue-Tracker#72]
版本1.16.5,
optato是9月22号半夜发布的那个版本？
1，焰魔释放的烈焰轰击和玩家释放的烈焰轰击都貌似不会消失，一直搁那不消失并造成伤害。
2，焰魔脚底的法阵变成普通火焰颜色了，这个我按照游戏里那个全局迷雾提示弄了没用。
（值得一提的是，装的焚天神兵模组里玩家脚底下的法阵是正常蓝色的）
3，烈焰轰击有时候飘起来的粒子里会混有一点点乱码材质？（无伤大雅）
4，试图更改炎葬的CD时间后，仍然只能按照灾变默认时间后再释放
（更值得一提的是，装了焚天神兵模组后，焰魔冷却时间期间右键居然也能招出法阵，只不过没法蓄力，单纯装帅用的，建议修掉）

**Comment by A0000Xz** [comment]
哦对了，焰魔脚下的那个法阵也不会消失，虽然这玩意并不造成伤害。

**Comment by Kasualix** [comment]
2.0.4修了
