### ISSUE TITLE
opotato还有些小特色

### ISSUE THREAD

**Issue by A0000Xz** [MCTeamPotato/Kasualix-Issue-Tracker#73]
游戏版本1.16.5
模组版本2.0.4
1，发现调节玩家放出的烈焰轰击尺寸后，每个火焰圈之间的距离不合理。打个比方，我把尺寸调成2.0与焰魔同步，结果放出来的圈是重合的。据观察焰魔释放的却并不重合。
（U1S1为什么要做这个功能呢，如果觉得这个没必要修的话就把这个调尺寸功能删除吧）
2，如果将烈焰轰击尺寸调的过大，并释放了很多，会导致游戏直接TPS骤降到几乎为0，可能是粒子效果也太多的缘故。
（所以我觉得这个尺寸调整的功能有点。。。。。）
3，玩家正常释放的1.0尺寸烈焰轰击发现在两个火焰圈之间一小块区域有时候会玄学的没有伤害判定，虽然区域很小，但焰魔放那里都甚至有几率不受伤，顶多吃个爆炸。
4，在炎葬的配置界面有个选择蓄力动画的设置，我不太明白是干什么用的。目前测试好像除了BOW以外的动画都会在右键后崩溃。
（这难道是做给史诗战斗模组用来兼容动画的嘛，难道要提供一个史诗战斗模式下释放烈焰轰击的动作？如果不是的话感觉这个配置功能好像没什么用啊，干脆删了比较好吧，我当时还寻思难道我能改成TRIDENT三叉戟动画放烈焰轰击嘛）
5，配置文件里你好像漏掉了末影守卫护手的配置

**Comment by A0000Xz** [comment]
补充一点，无论烈焰轰击设置尺寸多大，貌似收缩速度都是一样的。64尺寸的火焰圈收了半天。

**Comment by Kasualix** [comment]
> 发现调节玩家放出的烈焰轰击尺寸后，每个火焰圈之间的距离不合理。打个比方，我把尺寸调成2.0与焰魔同步，结果放出来的圈是重合的。据观察焰魔释放的却并不重合。 （U1S1为什么要做这个功能呢，如果觉得这个没必要修的话就把这个调尺寸功能删除吧）

本来就是图一乐的功能，做给我自己玩的，每次对准一个4*4的方块平台放出来一个差不多就得了。
 > 2，如果将烈焰轰击尺寸调的过大，并释放了很多，会导致游戏直接TPS骤降到几乎为0，可能是粒子效果也太多的缘故。 （所以我觉得这个尺寸调整的功能有点。。。。。）

带不动就别硬刚

 > 3，玩家正常释放的1.0尺寸烈焰轰击发现在两个火焰圈之间一小块区域有时候会玄学的没有伤害判定，虽然区域很小，但焰魔放那里都甚至有几率不受伤，顶多吃个爆炸。 

跟opotato没有关系

> 4，在炎葬的配置界面有个选择蓄力动画的设置，我不太明白是干什么用的。目前测试好像除了BOW以外的动画都会在右键后崩溃。 （这难道是做给史诗战斗模组用来兼容动画的嘛，难道要提供一个史诗战斗模式下释放烈焰轰击的动作？如果不是的话感觉这个配置功能好像没什么用啊，干脆删了比较好吧，我当时还寻思难道我能改成TRIDENT三叉戟动画放烈焰轰击嘛）

也就图一乐，没测过，崩了放崩溃报告
> 5，配置文件里你好像漏掉了末影守卫护手的配置

下次加
> 补充一点，无论烈焰轰击设置尺寸多大，貌似收缩速度都是一样的。64尺寸的火焰圈收了半天。

同1图一乐，这重要吗

**Comment by Kasualix** [comment]
护手配置已在2.0.5加入。
