### ISSUE TITLE
[1.20.1] [Dilemma] SStructures Reforged

### ISSUE THREAD

**Issue by Cixon** [MCTeamPotato/Kasualix-Issue-Tracker#74]
Hello again! I have a minor feature request regarding this mod.
I have a mod called [Philip's Ruins ](https://www.curseforge.com/minecraft/mc-mods/ruins)and it adds over 190 different types of structures to the overworld.

**Here's the issue:**
Finding other structures from other mods in the overworld is a near impossible feat due to the density of Philip's Ruins.
You may make the argument that I may adjust % rate however, I have a **better idea** without sacrificing distances.

Solution (feature request):

#For mod structures you DO NOT want affected from other structures and itself, write its modid down here
"structure modid list" = ["irons_spellbooks", "philipsruins"]

**Comment by Cixon** [comment]
I know I've been requesting a lot of stuff lately but if you could please add this for 1.20.1 I'd seriously appreciate it a lot!
It would be very very useful!

**Comment by Kasualix** [comment]
I tried, but failed to find a proper way to impl this.
