### ISSUE TITLE
[1.20.1] Redirectionor incompatibility with Sculk Horde

### ISSUE THREAD

**Issue by Z3R0Presence** [MCTeamPotato/Kasualix-Issue-Tracker#77]
when redirectionor is used alongside sculk horde, game crashes when opening a singleplayer world, or creating a world (not tested with multiplayer.

tested in isolation to ensure redirectionor is the incompatibility.

redirectionor version: 1.20.1-4.3.2
sculk horde: 1.20.1-0.7.0
geckolib: 4.2.3

latest: https://mclo.gs/wBNpFPR

reporting as per:
"Redirectionor is designed as compatible with every mod.

If you encounter any compatibility problem, pls create a new Issue on [my GitHub global issue tracker](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker)."

Please tell me if i should report this to the sculk horde dev as well.

**Comment by Kasualix** [comment]
You don't need report this to sculk horde dev
Can you try this build? https://filebin.net/mwprx4wpzxy1xa6p

**Comment by Z3R0Presence** [comment]
Hi, sorry for the late reply, the build link is not accessible for me.

**Comment by Kasualix** [comment]
[Unzip me.zip](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12728923/Unzip.me.zip)

**Comment by Z3R0Presence** [comment]
Thank you, will test now with just sculk horde :)

**Comment by Z3R0Presence** [comment]
The Game Still Crashes, same method to reproduce.

Latest: https://mclo.gs/zW2bX62

**Comment by Kasualix** [comment]
[UnzipMe.zip](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12729256/UnzipMe.zip)
This version should fix the crash.

**Comment by Z3R0Presence** [comment]
This version does fix the crash, Thanks for the quick fix 😄
