### ISSUE TITLE
[Forgeskyboxes]与papi-1.19.2-1.1.0不兼容

### ISSUE THREAD

**Issue by Staticlp** [MCTeamPotato/Kasualix-Issue-Tracker#78]
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12726626/latest.log)
[crash-2023-09-26_18.55.38-fml.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12726630/crash-2023-09-26_18.55.38-fml.txt)

另外我发现Forgeskyboxes的curseforge页面被移除了，这个项目中止开发了吗？

**Comment by Kasualix** [comment]
中止了。
