### ISSUE TITLE
Enhancement - Backports

### ISSUE THREAD

**Issue by wabeb325** [MCTeamPotato/Kasualix-Issue-Tracker#82]
I know it's annoying to ask a modder to do backports to 1.18, but it would be nice if you could in such a case with some of your mods like:
- ItemModelRefix - PingWheel Reforged - Safefall - ServerTickReforged - Sparse Structures Reforged - Rubidium Extras

"**Only if possible**", I don't want to sound persistent, this is just a suggestion.

**Comment by Kasualix** [comment]
For Rubidium Extras Potato Edition, it will be 1.16.5 only, go using vice's original mod if you need 1182 or above.
For ItemModelFixReforged, it will not be backported,  go using https://www.curseforge.com/minecraft/mc-mods/item-stitching-fix.
Others will be backported soon.

**Comment by wabeb325** [comment]
Good to know, thanks for the quick response ^^
