### ISSUE TITLE
(Bug) ItemModelFixReforged

### ISSUE THREAD

**Issue by Ninccino** [MCTeamPotato/Kasualix-Issue-Tracker#83]
The gaps are still there no matter which fix I select or item I hold.

Mods installed:
- ItemModelFixReforged (That's it)

![image](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/assets/68035002/a463d510-a970-48c3-95fa-243e8ecca4ca)

**Comment by Kasualix** [comment]
Just realized that [ModelGapFix](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix) has 1182+, ItemModelFixReforged is going to be archived.
