### ISSUE TITLE
Modern Inhibited - No potion effect on structures

### ISSUE THREAD

**Issue by NovaXCIV** [MCTeamPotato/Kasualix-Issue-Tracker#85]
I was looking for a protection mod and I found Modern Inhibited, a god-saver! But...
I'm testing it, and it does not seem to work. This is my current config:
```
[ModernInhibited]
	validStructures = ["uniquedungeons:desert_dungeon", "betterdeserttemples:desert_temple"]
```
Maybe I'm missing something or maybe it doesn't work with modded structures (?).

**Comment by Kasualix** [comment]
What's your game version?

**Comment by NovaXCIV** [comment]
Forge 1.19.2 (43.2.23+)

**Comment by Kasualix** [comment]
It should be fixed in [1.0.4](https://legacy.curseforge.com/minecraft/mc-mods/modern-inhibited/files/4784399)(Currently under review)

**Comment by NovaXCIV** [comment]
Tested and it works, thanks! One last thing, is it possible to give the effect without the particles?
like /effect give @p effect X X **true**

**Comment by Kasualix** [comment]
Ok, I will do it tomorrow, for now I'm already in bed
