### ISSUE TITLE
Enchantato - Enchantment Table Books

### ISSUE THREAD

**Issue by ANormalRaft** [MCTeamPotato/Kasualix-Issue-Tracker#87]
Forge 43.2.23
Enchentato Enchantment Table 1.19.2-0.0.1

The configuration works on armors and weapons but does not work on books. All enchantments still show up on books. I am using inverted mode

**Comment by Kasualix** [comment]
How about [0.0.2](https://legacy.curseforge.com/minecraft/mc-mods/enchantato-enchantment-table/files/4787184)?

**Comment by ANormalRaft** [comment]
Works, thanks a lot! :))
