### ISSUE TITLE
1.20.1 version?

### ISSUE THREAD

**Issue by opticGT** [MCTeamPotato/Kasualix-Issue-Tracker#89]
title says it all

**Comment by Kasualix** [comment]
title says nothing.
take a look at repo readme.

**Comment by WolfBV** [comment]
@opticGT Curseforge description: "This mod is unnecessary in Minecraft versions 1.19.2 or above because Mojang has already implemented the same caching there."

**Comment by WolfBV** [comment]
@opticGT 1.20.1 version of what?
