### ISSUE TITLE
Goal Optimizer 

### ISSUE THREAD

**Issue by ForestLive6** [MCTeamPotato/Kasualix-Issue-Tracker#9]
Hi Vampirism mod has been updated, is it possible now that Goal Optimizer will be running at full capacity? 
This is the log from the Vamprisim mod update:
"- modify instead of replacing target goals of vampire friendly mobs".
This is a link to github where the developers have provided an answer. 
https://github.com/TeamLapen/Vampirism/issues/1221

**Comment by Kasualix** [comment]
[I have already fixed it on my end](https://github.com/MCTeamPotato/GoalOptimizer/issues/4#issuecomment-1622936427)

**Comment by ForestLive6** [comment]
Is the removeGoal method working now? 
https://github.com/MCTeamPotato/GoalOptimizer/issues/2#issuecomment-1613430467

**Comment by Kasualix** [comment]
Yes.
