### ISSUE TITLE
Deathbutthree crash on 1.20.1 Quilt Modpack 

### ISSUE THREAD

**Issue by DragonshipZ** [MCTeamPotato/Kasualix-Issue-Tracker#90]
https://pastebin.com/m7P2TWeU

Deathbutthree crashes when attempting to run modded minecraft with it through PrismLauncher. Modpack works just fine without it but I would really like to include this mod. I can't seem to figure out what goes wrong with this mod in particular when I add it or if I'm missing something. I'm also not sure if this is a Quilt only issue as I've yet to test it out on Fabric but I wish to keep said modpack on Quilt so I'm hoping I can get it to work.

**Comment by Kasualix** [comment]
Fixed in 1.0.1
