### ISSUE TITLE
1.16.5, Crash when creating a world, Better End Potato Edition and Better Weather (Discontinued)

### ISSUE THREAD

**Issue by WolfBV** [MCTeamPotato/Kasualix-Issue-Tracker#92]
https://www.curseforge.com/minecraft/mc-mods/better-end-potato-edition

https://www.curseforge.com/minecraft/mc-mods/better-weather

Forge version 36.2.39
Better End Potato Edition version 2.10.5
Better Weather version 2.0.1

Pastebin of latest.log: https://pastebin.com/VgW9pXSU

[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/13201843/latest.log)

Pastebin of crash report:https://pastebin.com/yV25rveD

[crash-2023-10-30_00.15.03-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/13201845/crash-2023-10-30_00.15.03-server.txt)

**Comment by Kasualix** [comment]
how about this build?
