### ISSUE TITLE
Client closes with Redirector on 1710

### ISSUE THREAD

**Issue by Zilacon** [MCTeamPotato/Kasualix-Issue-Tracker#95]
When adding redirector on 1.7.10 the whole client closes within a minute from joining a server.
There is no logs, no crash logs, nothing. It just closes.
Before closing the GPU usage spikes to 100% (idk if this is relevant or not)

Pack attempting to use on: https://www.technicpack.net/modpack/gigapack-1710.1627683

Removing redirector stops this behavior.

**Comment by Kasualix** [comment]
https://github.com/MCTeamPotato/Redirector#issue-report

**Comment by Zilacon** [comment]
> https://github.com/MCTeamPotato/Redirector#issue-report

What does this mean? You didnt say anything and you linked to your read me...

**Comment by Kasualix** [comment]
> > https://github.com/MCTeamPotato/Redirector#issue-report
> 
> What does this mean? You didnt say anything and you linked to your read me...

I linked to the issue trackers  cuz there is wrong place for you to report issues
