### ISSUE TITLE
Does mobs no longer ticking mean they no longer despawn if too far away?

### ISSUE THREAD

**Issue by FelixRobotics** [MCTeamPotato/Kasualix-Issue-Tracker#96]
My game started out with higher fps but as soon as i ventured away from my house and near some big underground caves i got MASSIVE fps drops and my fps was still lower than normal when i got back to my house.  i'm assuming because i allow hostile mobs to break blocks with Special AI the fps drops were from all the tile entities so i've since disabled blocks broken by mobs to drop tile entities but i still wanted to know the answer to the title since you don't have comments on curseforge

**Comment by Kasualix** [comment]
No if you are installing incompatible mods.
