### ISSUE TITLE
[Remodifier Suggestion] Default generated file

### ISSUE THREAD

**Issue by Maypul** [MCTeamPotato/Kasualix-Issue-Tracker#99]
There is file that is always being generated if it is not created - violent.json. I understand that this is example but when I am using my naming scheme, it will always get regenerated. It's minor thing, but maybe possibly it can either be checked by loaded prefixed and if not existing generate it, or just create it only when there is no .toml file created yet.

My naming scheme for json files is attributetype-name.json so violent.json gets renamed to attack_speed-violent.json but violent.json still gets generated so it gets duplicated.

**Comment by Kasualix** [comment]
I can add one config option to define whether or not to generate it in the next version

**Comment by Kasualix** [comment]
https://github.com/MCTeamPotato/Remodifier/commit/dbe9a67c69cbc15d352d540e5b40852cad2fe396
